# Compatible with Architecture: x86_64 systems (Intel, AMD)
FROM adoptopenjdk/openjdk11:jre-11.0.7_10-alpine
COPY build/libs/spring-demo-1.0.0-SNAPSHOT.jar /spring-demo-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xms32m", "-Xms128M", "-jar","/spring-demo-1.0.0-SNAPSHOT.jar"]
