# Tested on AWS (m6g.large) ARM Graviton2 (Neoverse-N1), Architecture: aarch64
# Tested on AWS (a1.large)  ARM (Cortex-A72), Architecture: aarch64
# Tested on RaspberryPI 3 Model B+, ARM (Cortex-A53), Architecture: armv7l
FROM adoptopenjdk/openjdk11:armv7l-debianslim-jdk-11.0.7_10-slim
COPY build/libs/spring-proxy-1.0.0-SNAPSHOT.jar /spring-proxy-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xms32m", "-Xms128M", "-jar","/spring-proxy-1.0.0-SNAPSHOT.jar"]
